source 'https://www.rubygems.org'
gem 'cucumber'
gem 'capybara', '~> 2.15', '>= 2.15.1'
gem 'capybara-screenshot'
gem 'selenium-webdriver', '~> 2.53', '>= 2.53.4'
gem 'gherkin'
gem 'pry'
gem 'report_builder'
gem 'rspec', require: 'spec'